version: "3.4"

services:
  back-end:
    container_name: back-end
    image: back-end
    build: .
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    depends_on:
      - database
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: my-app
      POSTGRES_USER: my-app
      POSTGRES_PASSWORD: my-app
    ports:
      - 5432:5432
  database-adminer:
    container_name: database-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database

networks:
  default:
    name: my-app
